tomcat::params::http_port: 8082 
tomcat::params::https_port: 8443 
tomcat::params::ajp_port:  8009
tomcat::params::shutdown_port: 8006
tomcat::params::http_connection_timeout: 20000 
tomcat::params::https_max_threads: 150
tomcat::params::https_keystore: keystore
tomcat::params::https_keystore_pwd: password
tomcat::params::web_repository: http://ftp.unicamp.br/pub/apache/tomcat/tomcat-7/
